project:
  type: website

website:
  title: "Brancen Gregory"
  navbar:
    right:
      - posts.qmd
      - projects.qmd
      - icon: github
        href: https://github.com/brancengregory
      - icon: twitter
        href: https://twitter.com/brancengregory
format:
  html:
    theme: litera
    css: styles.scss



